#!/usr/bin/env zsh

PWD=$(cd "$(dirname "$0")";pwd)
source ${PWD}/../run_common.sh

LANGUAGE="clang"
EXECUTES=(
    basic
    memory
    struct
    union
    enum
    preprocessor
    file
    arg
    string
)

prompt
read_arg $1
mk_build

if [[ -n "$name" ]]; then
    echo "Run ${name}"
    clang -fdiagnostics-color=always \
        -g ${name}.c extern.c \
        -o .build/${name} &&
        ./.build/${name}
    echo $?
fi
