#!/usr/bin/env zsh

PWD=$(cd "$(dirname "$0")";pwd)
source ${PWD}/../run_common.sh

LANGUAGE="go"
EXECUTES=(
    hello
)

prompt
read_arg $1

if [[ -n "${name}" ]]; then
    echo "Run ${name}.go"
    go run ${name}.go
    echo $?
fi
