#!/usr/bin/env zsh

PWD=$(cd "$(dirname "$0")";pwd)
source ${PWD}/../run_common.sh

LANGUAGE="swift"
EXECUTES=(
	hello
	basic
	character
	collection
	controlFlow
	closures
	enumeration
	classes
	subscript
	inheritan
	optionals
	errorHandle
	typeCasting
	nestedType
	protocols
	generics
	concurrency
)

prompt
read_arg $1
mk_build

if [[ -n "$name" ]]; then
	echo "Run ${name}"
	swift run $name
	echo $?
fi
