#!/usr/bin/env zsh

PWD=$(cd "$(dirname "$0")";pwd)
source ${PWD}/../run_common.sh

LANGUAGE="nasm"
EXECUTES=(
    hello
)

prompt
read_arg $1
mk_build

if [[ -n "$name" ]]; then
	echo "Run ${name}"
    nasm -f macho64 $name.asm -o .build/$name.o && \
        ld -e start -static .build/$name.o -o .build/$name && \
        .build/$name
    echo $?
fi
